<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Try_catch.aspx.cs" Inherits="Try_catch" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <% try
        {
            int nb = Int32.Parse(Request.QueryString["toto"]);
            if (nb == 0)
            {
                Response.Write("Il n'est pas possible de faire une division par zéro");
            }
            else
            {
                int val = 0;
                val = 100 / nb;
                Response.Write("<br><font color='red'>Résultat de la division de 100 par le parametre "+nb+" : " + val.ToString()+"</font>");
            }
        }
        catch (Exception e)
        {
            Response.Write("Une exception est levée:\""+e.Message+ "\"");
        }
         %>
    </div>
    </form>
</body>
</html>
